# SPDX-License-Identifier: GPL-2.0+

obj-y	+= simaai_ddrphy_init.o simaai_ethphy_init.o phy_init.o firmware_ddr.o init_ddr_zebu.o \
	    init_ddr_933MHz.o init_ddr_800MHz.o init_ddr_533MHz.o ddr_phy_debug.o init_eth_phy.o \
	    shmem.o simaai_ddr_utils.o
