//////////////////////////////////////////////////////////////////////////
// *** DO NOT MODIFY ***
// This file was generated by common/bin/print_ipxact_addr_map.py
// For usage refer to the source of that script
//////////////////////////////////////////////////////////////////////////
#ifndef _GPIO_ADDR_MAP__H
#define _GPIO_ADDR_MAP__H
#define GPIO_REG__GPIO_SWPORTA_DR_ADDR 0x00000000
#define GPIO_REG__GPIO_SWPORTA_DDR_ADDR 0x00000004
#define GPIO_REG__GPIO_SWPORTA_CTL_ADDR 0x00000008
#define GPIO_REG__GPIO_INTEN_ADDR 0x00000030
#define GPIO_REG__GPIO_INTMASK_ADDR 0x00000034
#define GPIO_REG__GPIO_INTTYPE_LEVEL_ADDR 0x00000038
#define GPIO_REG__GPIO_INT_POLARITY_ADDR 0x0000003c
#define GPIO_REG__GPIO_INTSTATUS_ADDR 0x00000040
#define GPIO_REG__GPIO_RAW_INTSTATUS_ADDR 0x00000044
#define GPIO_REG__GPIO_PORTA_EOI_ADDR 0x0000004c
#define GPIO_REG__GPIO_EXT_PORTA_ADDR 0x00000050
#define GPIO_REG__GPIO_LS_SYNC_ADDR 0x00000060
#define GPIO_REG__GPIO_ID_CODE_ADDR 0x00000064
#define GPIO_REG__GPIO_INT_BOTHEDGE_ADDR 0x00000068
#define GPIO_REG__GPIO_VER_ID_CODE_ADDR 0x0000006c
#define GPIO_REG__GPIO_CONFIG_REG2_ADDR 0x00000070
#define GPIO_REG__GPIO_CONFIG_REG1_ADDR 0x00000074
#endif // _GPIO_ADDR_MAP__H
