//////////////////////////////////////////////////////////////////////////
// *** DO NOT MODIFY ***
// This file was generated by common/bin/print_addr_map.py
// For usage refer to the source of that script
//////////////////////////////////////////////////////////////////////////
#ifndef _SIO_ADDR_MAP__H
#define _SIO_ADDR_MAP__H
#define SIO_REG__SIO_ID_ADDR 0x00000000
#define SIO_REG__SIO_RT_ADDR 0x00000040
#define SIO_REG__SIO_PDN_ADDR 0x00000104
#define SIO_REG__SIO_PUP_ADDR 0x00000108
#define SIO_REG__SIO_HYS_ADDR 0x0000010c
#define SIO_REG__SIO_STR_ADDR 0x00000110
#define SIO_REG__SIO_SLEW_ADDR 0x00000114
#define SIO_REG__SIO_OE_ADDR 0x00000118
#define SIO_REG__SIO_IE_ADDR 0x0000011c
#define SIO_REG__SIO_ODEM_ADDR 0x00000120
#define SIO_REG__SIO_ODPOL_ADDR 0x00000124
#define SIO_REG__SIO_MX1_ADDR 0x00000204
#define SIO_REG__SIO_MX2_ADDR 0x00000208
#define SIO_REG__SIO_RSTCLR_ADDR 0x00000210
#define SIO_REG__SIO_RSTSET_ADDR 0x00000214
#define SIO_REG__SIO_TRIG__REGISTER_ARRAY_SIZE 4
#define SIO_REG__SIO_TRIG__REGISTER_ARRAY_ADDR 0x00000220
#define SIO_REG__SIO_SIRQ_ADDR 0x00000230
#define SIO_REG__SIO_DIV__REGISTER_ARRAY_SIZE 10
#define SIO_REG__SIO_DIV__REGISTER_ARRAY_ADDR 0x00000300
#endif // _SIO_ADDR_MAP__H
